### ISSUE TITLE
unit mqtt

### ISSUE THREAD

**Issue by John7505** [prof7bit/fpc-mqtt-client#2]
Hi,

I also get a range error below.
function TMQTTClient.GetNewPacketID: UInt16;
begin
  // fixme
  Lock;
  try
    Result := FNextPacketID;
    if Result = 0 then // IDs must be non-zero, so we skip the zero
      Result := 1;

    FNextPacketID := Result + 1;  --- Range Issue
  finally
    Unlock;
  end;
end;

**Comment by philduvlu** [comment]
Hello,

Thank you for your development MQTT that will help me with my Lazarus v4.0 !

For the "newbies" in Lazarus as me, consider also installing OpenSSL (slproweb.com/products/Win32OpenSSL.html, light version is enough), noting the names of the DLLs installed in the System (c:\windows\system32), and modifying openssl.pas accordingly in the OpenSSL package of the FPC directory (\lazarus\fpc\3.2.2\source\packages\openssl\src) :

DLLSSLName3: string = {$IFDEF WIN64}'libssl-1_1-x64.dll'{$ELSE}'libssl-1_1.dll'{$ENDIF};
  DLLUtilName: string = 'libeay32.dll';
  DLLUtilName2: string = {$IFDEF WIN64}'libcrypto-1_1-x64.dll'{$ELSE}'libcrypto-1_1.dll'{$ENDIF};
to:
DLLSSLName3: string = {$IFDEF WIN64}'libssl-3-x64.dll'{$ELSE}'libssl-3.dll'{$ENDIF};
  DLLUtilName: string = 'libeay32.dll';
  DLLUtilName2: string = {$IFDEF WIN64}'libcrypto-3-x64.dll'{$ELSE}'libcrypto-3.dll'{$ENDIF};

Nothing to change to running the application to accepting SSL connection.  The files client.crt and client.key have not not to be present, I have just the ca.crt generated by the server installed on my client and all is working fine now.

It is my small contribution to your project, if that can help someone else in order to avoid to lose time like I did by searching and trying lot of various things.  Note that your project is the best, the more completed and finished that I found and tried, thank you.

Kind Regards,
Ph. Duvivier

[openssl.pas.zip](https://github.com/user-attachments/files/21410210/openssl.pas.zip)
